name: web_router
version: 0.0.2
author: Alex Nichol <unixpickle@gmail.com>
description: A simple and extensible web framework
homepage: https://github.com/unixpickle/router
dependencies:
  path: 1.3.0
